name: live_call_widget_flutter
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0


flutter_gen:
  output: lib/generated/assets/
  line_length: 80

  integrations:
    flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
   assets:
     - assets/svg/call_button.svg
     - assets/svg/close_btn.svg
     - assets/svg/company_logo.svg
     - assets/svg/powered_pressone.svg


   fonts:
     - family: AvertaDemoPECuttedDemo
       fonts:
         - asset: assets/fonts/AvertaDemoPECuttedDemo-Regular.otf
           weight: 400
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
